language: java
jdk: oraclejdk8
before_install:
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi
  - nvm install 7.8.0
  - nvm use 7.8.0
  - npm i -g karma karma-cli karma-jasmine karma-phantomjs-launcher jasmine-core phantomjs-prebuilt
script: ./gradlew clean npm_install npmBuild npmTest build
addons:
    code_climate:
        repo_token: 2a51c2a4894be699e9adab5eea8e19006f71fa6109c48273ec3af7bf07556fcd