version: '2'
services:
  app:
    build: .
    depends_on:
      - cassandra
      - elastic
  cassandra:
    image: cassandra:2.2.5
    ports:
      - "9042"
  elastic:
    image: elasticsearch:2.3.3
    expose:
      - "9200"
      - "9300"