server:
  port: ${port:9000}
  compression:
    enabled: true
    mime-types: application/json

spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:mem:filmfox
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: none

flyway:
  locations: classpath:db/migration/schema, classpath:db/migration/data
  schemas: filmfox